### ISSUE TITLE
if statement problem in CBN.py

### ISSUE THREAD

**Issue by andgitchang** [Howal/Cross-iterationBatchNorm#2]
The work is really inspiring, in terms of dealing with high variance of small mini-batch size BN statistics, while keeps the conventional property of BN fusion during inference.

However, I am confused with the following fraction of codes:
https://github.com/Howal/Cross-iterationBatchNorm/blob/90b1b17ca1b7b492449dacd311e8fabfb773fb25/mmdet/models/utils/CBN.py#L86

Assume `self.buffer_num, self.burnin` are given. 
`self.pre_mu` was initialized as an empty list, and appended inside the "if condition scope" itself:
https://github.com/Howal/Cross-iterationBatchNorm/blob/90b1b17ca1b7b492449dacd311e8fabfb773fb25/mmdet/models/utils/CBN.py#L108

It seems that one would never reach the condition from scratch, for which `len(self.pre_mu)==self.buffer_num` doesn't hold.
Is there anything misunderstood? Thanks.

**Comment by Howal** [comment]
Hi @andgitchang . Thanks for pointing that out.
It should be a mistake when merging the code.
I have delete the last condition, and will double check with the original code.
