### ISSUE TITLE
关于CBN的keras或tf实现

### ISSUE THREAD

**Issue by FL77N** [Howal/Cross-iterationBatchNorm#3]
你好，可以用keras或者tensorflow实现一下CBN吗？还有就是直接用python实现的CBN速度上会不会收到影响呢？

**Comment by Howal** [comment]
Current implementation is based on PyTorch which uses C/CUDA as the backend. If you use python directly, there definitely will be a performance drop.

**Comment by FL77N** [comment]
> Current implementation is based on PyTorch which uses C/CUDA as the backend. If you use python directly, there definitely will be a performance drop.

Thanks for your reply!
