### ISSUE TITLE
Can CBN be combined with SyncBN to take advances of both (multiple GPUs)

### ISSUE THREAD

**Issue by chuong98** [Howal/Cross-iterationBatchNorm#5]
Hi, the question is in the title. THank you.

**Comment by Howal** [comment]
Yes, you can use them together. But I don't expect to get any results better than using them separately.
Because each of them already provides enough batchs for statistic estimation.
(Just like increase bs from 32 to 64 with BN.)

**Comment by chuong98** [comment]
Ok, thanks. Is this already supported? Since, like SpineNet they train the NW with very large batch size 256. I hope we can combine both

**Comment by Howal** [comment]
Sorry, it's not supported by this repo.
